name: PoetGeek
favicon: null
layout_spectrum: 1
typography_spectrum: 0.89774
title: PoetGeek - Eric Williamson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#500500'
    - '#d9cecc'
    - '#a99f8e'
    - '#675f4b'
  brandStrength: 0.5
  lightness: 0.4600597301032394
  saturation: 0.7250865481328219
  rhythmicContrast: 0.5589220747351646
purpose: []
