name: PoetGeek
favicon: null
layout_spectrum: 0.20446741627529263
typography_spectrum: 0.07617008383385837
title: PoetGeek - Eric Williamson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6668687877245247
  lightness: 0.4600597301032394
  saturation: 0.7250865481328219
  rhythmicContrast: 0.5589220747351646
purpose: []
